version: 1.0.{build}
image: Ubuntu2004
build: off
test: off

environment:
  matrix:
    - PART: 1
    - PART: 2
    - PART: 3
    # Add more jobs (up to PART: 20) after testing

build_script:
  - echo "=== Job for PART=$PART ==="
  - echo "Updating package lists..."
  - sudo apt-get update
  - echo "Installing git..."
  - sudo apt-get install -y git
  - echo "Cloning repository..."
  - git clone https://github.com/Fiujol/android
  - echo "Listing cloned directory..."
  - ls -la
  - echo "Changing to android directory..."
  - cd android
  - echo "Checking for start.sh..."
  - ls -la start.sh || exit 1
  - echo "Making start.sh executable..."
  - chmod +x start.sh
  - echo "Environment details:"
  - env
  - echo "Running start.sh with PART=$PART..."
  - timeout 58m bash start.sh 8 && echo "start.sh completed successfully for PART=$PART" || echo "start.sh failed or timed out for PART=$PART"
